### ISSUE TITLE
support for multiple instances

### ISSUE THREAD

**Issue by billimek** [mxschmitt/golang-url-shortener#117]
I experimented with running multiple instances of this app in order to HA/reliability and not a single point of failure.

It quickly became apparent that this was problematic, I believe, due to how session state is handled.

It would be great if we could run this in a multi-instance format (e.g. docker swarm, k8s, cloudfoundry, etc) such that we don't encounter scenarios where one app runtime is holding state (either in memory or on local disk to that instance) and throws errors for the browser-based interactions of an authenticated user.

As an experiment, I modified the sessions configuration in `auth.go` to leverage the [redis-based sessions management](https://github.com/gin-gonic/contrib/tree/master/sessions#redis) as seen with [this commit](https://github.com/billimek/golang-url-shortener/commit/db068b54ab0b8b868ea87b7f73279d69861fc742) to do something like this:

```golang
	// use redis as the session store if it is configured
	switch backend := util.GetConfig().Backend; backend {
	case "redis":
		store, _ := sessions.NewRedisStore(10, "tcp", util.GetConfig().Redis.Host, util.GetConfig().Redis.Password, []byte("secret"))
		h.engine.Use(sessions.Sessions("backend", store))
	default:
		h.engine.Use(sessions.Sessions("backend", sessions.NewCookieStore(util.GetPrivateKey())))
	}
```

However, this didn't actually fully work which leads me to believe that additional changes may be required.

The purpose of this issue is to open the discussion about the possibility and approaches for supporting multiple instances of the application running at the same time.

**Comment by billimek** [comment]
Digging into this and keeping a log of activities here for others to benefit:

The app-as-is when running with 3 instances fails during github oath with the following error in the browser: `{"error":"invalid session state: %!s(\u003cnil\u003e)"}`

The app logs show, `[sessions] ERROR! securecookie: the value is not valid`

Other times the UI will flash a red badge with `Could not fetch check: incorrect response status code: 401; text: Unauthorized` and error logs will show, `Could not parse auth data: could not parse token: signature is invalid`.  Refreshing over and over sometimes shows us the app UI as the authenticated user.  This supports the notion that multiple instances are working such that only one of the instances are properly holding the session/auth state.

**Comment by billimek** [comment]
When implementing redis as a sessions backend instead of cookies ([changes](https://github.com/mxschmitt/golang-url-shortener/compare/master...billimek:redis_session?expand=1)), we no longer see the `{"error":"invalid session state: %!s(\u003cnil\u003e)"}` errors but do still see occasionally the same extra issue above,

The UI will flash a red badge with Could not fetch check: incorrect response status code: `401; text: Unauthorized` and error logs will show, `Could not parse auth data: could not parse token: signature is invalid.` Refreshing over and over sometimes shows us the app UI as the authenticated user. This supports the notion that multiple instances are working such that only one of the instances are properly holding the session/auth state.

**Comment by billimek** [comment]
One more update.  It appears that the issue described above was a mismatch of the value returned from [GetPrivateKey()](https://github.com/mxschmitt/golang-url-shortener/blob/master/internal/util/private.go#L37) which appears to be, by default, a random key unique to each running instance.

It seems that for instances of multiple instances, a common shared private key must be used for purposes of decoding session state information when stored in a common backend like redis.

Here is an updated example [set of changes](https://github.com/mxschmitt/golang-url-shortener/compare/master...billimek:redis_session?expand=1) that would accomplish this by encoding the static string "secret" for `GetPrivateKey()` to return.  This doesn't seem like the right approach.  Any ideas?

**Comment by billimek** [comment]
@memory yes this is a great idea!

I'll do that and PR something for review. Does it seem reasonable to assume that session storage should be in redis (hard-coded to db 1 and not db 0 so as to not be in the same space as the app data) if the app is configured to use redis, or should it be an additional configurable choice?

**Comment by memory** [comment]
Rather than hard-coding it, I'd make the default DB1 but have a runtime check to make sure that session storage and data storage aren't using the same db.

As things stand right now I think it's reasonable that session storage would use redis if data storage is, but beware that I'm hoping to add at least one more data backend (probably postgres, possibly cloud spanner) in the near future and it might make sense to use redis for sessions even if someone is using a different data storage backend, so try not to foreclose on that. :)

**Comment by billimek** [comment]
Closed via #119

**Comment by vitalyzhakov** [comment]
Hello!

@billimek , is #119 solves all HA issues?

**Comment by billimek** [comment]
> Hello!
> 
> @billimek , is #119 solves all HA issues?

Hi @vitalyzhakov, yes I believe so - assuming you are using the redis instance as described in #119
