### ISSUE TITLE
ShareX shortened URLs result in error

### ISSUE THREAD

**Issue by nightah** [mxschmitt/golang-url-shortener#120]
It appears that any URL that's created with the ShareX configuration that is generated for a user results in the following error message:
```
could not get and crease visitor counter: entry is expired, 
<a href="/?customUrl=cgkDUm">Temporary Redirect</a>.
```

I can also see the following when debug logging is turned on within the container logs:
```
[GIN-debug] [WARNING] Headers were already written. Wanted to override status code 500 with 307
INFO[0975]                                               fields.time="2018-08-13T09:28:39Z" ip=10.10.10.254 latency="185.374µs" method=GET path=/cgkDUm status=307 user-agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36"
```

It appears to think that anything created via ShareX is expired, however anything created from the front-end works.

Do we need to pass an additional header in to ensure that expiration does not immediately occur?

**Comment by nightah** [comment]
@mxschmitt sorry to be a pain, is there any feedback on this?
As far as I can tell this will not work with ShareX based on the default provided configuration, unless there's something I appear to be missing?
Since there isn't a specific API definition I can't tell if there's a missing parameter for the ShareX config, could you please advise?

**Comment by mxschmitt** [comment]
@nightah it should be fixed now and I cannot reproduce it anymore on my test environment. :)

**Comment by nightah** [comment]
@mxschmitt confirmed that this is now resolved, thanks!
